
// finally 始终执行
try {
    console.log('try')
    return
    
} catch (error) {
    
} finally {
    console.log('finally is called')
}